#!/bin/sh

if test -z "$1" -o "$1" = '-h' -o "$1" = '--help'
then
    echo "Usage: $(basename "$0") <date>"
    echo 'Date example: Thu, 07 Apr 2005 22:13:13 +0200'
    exit 1
fi

DATE="$1"
shift

GIT_AUTHOR_DATE="$DATE" GIT_COMMITTER_DATE="$DATE" git commit "$@"
