#!/bin/sh

usage()
{
    printf 'Usage: %s <date> [git commit args...]\n' "$(basename "$0")"
    echo 'Date example: Thu, 07 Apr 2005 22:13:13 +0200'
    exit 1
}

if test $# -lt 1
then
    usage
fi

date="$1"
shift

GIT_AUTHOR_DATE="$date" GIT_COMMITTER_DATE="$date" git commit "$@"
