#!/bin/sh

usage()
{
    printf 'Usage: %s [-p] <file> [name]\n' "$(basename "$0")"
    exit 1
}

if test "$1" = '-p' -o "$1" = '--permanent'
then
    file="$2"
    permanent=1
    name="$3"
else
    file="$1"
    permanent=0
fi

if test -z "$file"
then
    echo 'Missing file name.'
    usage
fi

if test ! -f "$file"
then
    printf '%s is not a regular file.\n' "$file"
    usage
fi

filesize=$(wc -c < "$file")

if test $filesize -ge 128000000
then
    printf '%s is too large (expected less than 128MB, got %d).\n' "$file" $filesize
    usage
fi

if test -z "$name"
then
    name="$(basename "$file")"
fi

temp="$(mktemp)"
code=$( \
    curl -s -X POST -o "$temp" -w '%{http_code}' \
        -F file=@"$file" \
        -F name="$name" \
        -F permanent=$permanent \
        -F secret="$(cat ~/bin/upload-secret)" \
        'https://up.clayton.cc/upload-bash.php' \
)

if test $code -eq 200
then
    printf 'Upload complete: %s\n' "$(cat "$temp")"

    if test -e /dev/clipboard
    then
        cat "$temp" > /dev/clipboard
    fi
else
    printf 'Upload failed: %s\n' "$(cat "$temp")"
fi

rm "$temp"
